"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createEvent, deleteEvent, getAdmissions, getEvents, type Admission, type CalendarEvent, WorkspaceApiError } from "../workspace/api";

const format = (value: string) => new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value));
export function RealCalendar() {
  const [personal, setPersonal] = useState<readonly CalendarEvent[]>([]); const [admissions, setAdmissions] = useState<readonly Admission[]>([]); const [state, setState] = useState("loading"); const [message, setMessage] = useState("");
  const load = () => void Promise.all([getEvents(), getAdmissions()]).then(([events, official]) => { setPersonal(events); setAdmissions(official); setState("ready"); }).catch((error: WorkspaceApiError) => { setState(error.status === 401 ? "unauthorized" : "error"); setMessage(error.status === 401 ? "Your session has expired. Please log in again." : "Could not load calendar data."); });
  useEffect(load, []);
  async function add(data: FormData): Promise<void> { const title = String(data.get("title") || "").trim(); const date = String(data.get("date") || ""); if (!title || !date) { setMessage("A title and date are required."); return; } setMessage("Saving…"); try { const event = await createEvent({ title, date, kind: String(data.get("kind")) as CalendarEvent["kind"], labId: null, memo: String(data.get("memo") || "") || null }); setPersonal((items) => [...items, event].sort((a, b) => a.date.localeCompare(b.date))); setMessage("Event added."); } catch (error) { const apiError = error as WorkspaceApiError; setMessage(apiError.status === 401 ? "Your session has expired. Please log in again." : "Could not save the event."); } }
  async function remove(id: string): Promise<void> { try { await deleteEvent(id); setPersonal((items) => items.filter((item) => item.id !== id)); } catch { setMessage("Could not delete the event. It remains in your calendar."); } }
  async function download(): Promise<void> { try { const response = await fetch("/api/backend/admissions/export.ics"); if (!response.ok) throw new Error(); const blob = await response.blob(); if (!blob.type.includes("calendar")) throw new Error(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "admissions-calendar.ics"; link.click(); URL.revokeObjectURL(url); } catch { setMessage("Could not export the ICS calendar."); } }
  if (state === "loading") return <main className="calendar-layout"><p role="status">Loading calendar…</p></main>; if (state === "unauthorized") return <main className="calendar-layout"><p>{message}</p><Link href="/login">Log in</Link></main>;
  return <main className="calendar-layout"><header className="calendar-heading"><div><p className="calendar-kicker">ADMISSIONS CALENDAR</p><h1>Plan your application dates</h1><p>Personal reminders and sourced admissions events are shown separately.</p></div><button type="button" onClick={() => void download()}>Export admissions ICS</button></header>{state === "error" && <p role="alert">{message} <button onClick={load} type="button">Try again</button></p>}<section className="calendar-content"><div className="calendar-month-panel"><h2>My events</h2><form action={(data) => void add(data)} className="calendar-filter"><input name="title" placeholder="Event title" required /><input name="date" type="date" required /><select name="kind" defaultValue="apply"><option value="apply">Application</option><option value="contact">Contact</option><option value="docs">Documents</option><option value="interview">Interview</option></select><input name="memo" placeholder="Optional note" /><button type="submit">Add event</button></form>{personal.length ? <ol className="calendar-agenda">{personal.map((event) => <li key={event.id}><div className="calendar-event-copy"><h3>{event.title}</h3><p>{format(event.date)} · {event.kind}</p>{event.memo && <small>{event.memo}</small>}<button onClick={() => void remove(event.id)} type="button">Delete</button></div></li>)}</ol> : <p>No personal events yet.</p>}</div><aside className="calendar-upcoming"><h2>Official admissions dates</h2>{admissions.length ? <ol className="calendar-agenda">{admissions.map((event) => <li key={event.id}><div className="calendar-event-copy"><div className="calendar-badges"><span>{event.eventType}</span>{event.isDeadlineImminent && <span>Deadline soon</span>}</div><h3>{event.title}</h3><p>{format(event.startAt)}{event.endAt ? ` – ${format(event.endAt)}` : ""}</p>{event.description && <small>{event.description}</small>}<p><a href={event.sourceUrl} rel="noreferrer" target="_blank">Source</a>{event.lastVerifiedAt && ` · Checked ${format(event.lastVerifiedAt)}`}</p></div></li>)}</ol> : <p>No official admissions dates are available.</p>}</aside></section><p aria-live="polite">{message}</p></main>;
}
