"use client";

import ky, { HTTPError } from "ky";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { LabDetail, LabSummary } from "../../server/backend/labs";

type Props = Readonly<{ lab: LabDetail }>;
const dateFormatter = new Intl.DateTimeFormat("en-US", { dateStyle: "long", timeZone: "Asia/Seoul" });
function value(fact: LabDetail["facts"][number]): string { return fact.valueText ?? (fact.valueNumber === null ? "Unavailable" : String(fact.valueNumber)); }
export function RealLabDetail({ lab }: Props) {
  const [similar, setSimilar] = useState<readonly LabSummary[] | null>(null); const [similarError, setSimilarError] = useState(false);
  useEffect(() => { void ky.get(`/api/backend/labs/${lab.id}/similar`).json<{ items: LabSummary[] }>().then((result) => setSimilar(result.items)).catch(() => setSimilarError(true)); }, [lab.id]);
  return <main className="catalog-page"><Link className="catalog-detail-link" href="/professors">Back to lab search</Link><header className="catalog-hero"><p className="catalog-kicker">POSTECH LAB</p><h1>{lab.name}</h1><p>{lab.professorName} · {lab.department} · {lab.field}</p><ul className="catalog-topic-list">{lab.keywords.map((keyword) => <li key={keyword}>{keyword}</li>)}</ul></header><div className="catalog-workspace"><section className="profile-recommendation"><h2>Lab overview</h2><p>{lab.summary ?? "A summary was not provided by the source."}</p><dl><div><dt>University</dt><dd>{lab.university}</dd></div><div><dt>Location</dt><dd>{lab.location ?? "Unavailable"}</dd></div><div><dt>Contact</dt><dd>{lab.contactEmail ?? "Unavailable"}</dd></div></dl>{lab.contactEmail && <Link href={`/contact?professor=${encodeURIComponent(lab.id)}`}>Create contact email draft</Link>}</section><section className="profile-recommendation"><h2>Lab facts</h2>{lab.facts.length ? <ul>{lab.facts.map((fact, index) => <li key={`${fact.factType}-${index}`}><strong>{fact.factType}:</strong> {value(fact)} {fact.sourceUrl && <a href={fact.sourceUrl} rel="noreferrer" target="_blank">Source</a>}</li>)}</ul> : <p>No additional facts are available.</p>}</section><section className="profile-recommendation"><h2>Recent papers</h2>{lab.papers.length ? <ol>{lab.papers.map((paper) => <li key={paper.id}><strong>{paper.title}</strong> ({paper.publishedYear}){paper.venue && ` · ${paper.venue}`}<p>{paper.summary ?? paper.abstract ?? "No abstract or summary is available."}</p>{paper.paperUrl && <a href={paper.paperUrl} rel="noreferrer" target="_blank">Paper link</a>}</li>)}</ol> : <p>No paper records are available for this lab.</p>}</section><section className="profile-recommendation"><h2>Sources and freshness</h2>{lab.sourceUrl ? <p><a href={lab.sourceUrl} rel="noreferrer" target="_blank">Original source</a></p> : <p>Source URL unavailable.</p>}<p>Last checked: {lab.sourceCheckedAt ? dateFormatter.format(new Date(lab.sourceCheckedAt)) : dateFormatter.format(new Date(lab.updatedAt))}</p>{lab.homepageUrl && <a href={lab.homepageUrl} rel="noreferrer" target="_blank">Lab homepage</a>}</section><section className="profile-recommendation"><h2>Similar labs</h2>{similarError ? <p>Similar labs could not be loaded right now.</p> : similar === null ? <p>Loading similar labs…</p> : similar.length ? <ul>{similar.map((item) => <li key={item.id}><Link href={`/professors/${item.id}`}>{item.name}</Link> · {item.professorName}</li>)}</ul> : <p>No similar labs were returned.</p>}</section><FavoriteControl labId={lab.id} /></div></main>;
}
function FavoriteControl({ labId }: Readonly<{ labId: string }>) { const [saved, setSaved] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); useEffect(() => { void ky.get("/api/backend/me/favorites").json<{ labIds: string[] }>().then((value) => setSaved(value.labIds.includes(labId))).catch(() => setMessage("Log in to manage saved labs.")); }, [labId]); async function toggle() { setBusy(true); try { await (saved ? ky.delete(`/api/backend/me/favorites/${labId}`) : ky.put(`/api/backend/me/favorites/${labId}`)); setSaved((value) => !value); setMessage(saved ? "Removed from saved labs." : "Saved lab."); } catch (error) { if (error instanceof HTTPError && error.response.status === 401) window.location.assign("/login"); else setMessage("Could not update saved labs. Your previous state was kept."); } finally { setBusy(false); } } return <section className="profile-recommendation"><button className="catalog-save-button" disabled={busy} onClick={() => void toggle()} type="button">{busy ? "Saving" : saved ? "Remove saved lab" : "Save lab"}</button><p aria-live="polite">{message}</p></section>; }
