"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { getAdmissions, getEvents, getFavorites, getLatestAnalysis, getProfile, getRecommendations, type Admission, type CalendarEvent, type Recommendation, type UserProfile, WorkspaceApiError } from "../workspace/api";
import styles from "./dashboard.module.css";

export function DashboardHome() {
  const [profile, setProfile] = useState<UserProfile | null>(null); const [recommendations, setRecommendations] = useState<readonly Recommendation[]>([]); const [events, setEvents] = useState<readonly CalendarEvent[]>([]); const [admissions, setAdmissions] = useState<readonly Admission[]>([]); const [cv, setCv] = useState(false); const [saved, setSaved] = useState(0); const [state, setState] = useState("loading");
  useEffect(() => { void Promise.all([getProfile(), getRecommendations().catch((error: WorkspaceApiError) => error.status === 404 ? [] : Promise.reject(error)), getEvents(), getAdmissions(), getLatestAnalysis().then(() => true).catch((error: WorkspaceApiError) => error.status === 404 ? false : Promise.reject(error)), getFavorites()]).then(([me, matches, personal, official, hasCv, favorites]) => { setProfile(me); setRecommendations(matches); setEvents(personal); setAdmissions(official); setCv(hasCv); setSaved(favorites.length); setState("ready"); }).catch((error: WorkspaceApiError) => setState(error.status === 401 ? "unauthorized" : "error")); }, []);
  if (state === "loading") return <main className={styles["page"]}><p role="status">Loading your dashboard…</p></main>; if (state === "unauthorized") return <main className={styles["page"]}><p>Your session has expired.</p><Link href="/login">Log in</Link></main>; if (state === "error") return <main className={styles["page"]}><p>Could not load dashboard data.</p></main>;
  const next: readonly [string, "/cv" | "/professors" | "/contact"] = !cv ? ["Upload a CV", "/cv"] : !recommendations.length ? ["Review recommendations", "/professors"] : !saved ? ["Save a lab", "/professors"] : ["Create outreach draft", "/contact"];
  const upcoming = [...events.map((event) => ({ title: event.title, date: event.date, type: "Personal" })), ...admissions.filter((event) => !event.isEnded).map((event) => ({ title: event.title, date: event.startAt, type: "Admissions" }))].sort((a, b) => a.date.localeCompare(b.date)).slice(0, 4);
  return <main className={styles["page"]}><header className={styles["pageHeader"]}><div><h1>Welcome{profile?.name ? `, ${profile.name}` : ""}</h1><p>Review your real profile, CV analysis, recommendations, and dates.</p></div><Link href={next[1]}>Next: {next[0]}</Link></header><section className={styles["statusStrip"]}><div><span>CV analysis</span><strong>{cv ? "Available" : "Not uploaded"}</strong></div><div><span>Recommendations</span><strong>{recommendations.length}</strong></div><div><span>Saved labs</span><strong>{saved}</strong></div></section><div className={styles["workspaceGrid"]}><section className={styles["feedSection"]}><div className={styles["sectionHeader"]}><div><h2>Recommended labs</h2><p>Generated from your latest CV analysis.</p></div><Link href="/professors">View all</Link></div>{recommendations.length ? <ol className={styles["professorList"]}>{recommendations.slice(0, 4).map((item) => <li key={item.labId}><Link className={styles["professorRow"]} href={`/professors/${item.labId}`}><div><h3>{item.labName}</h3><p>{item.professorName}</p><p>{item.shortReason}</p></div><strong>{item.totalScore.toFixed(1)}</strong></Link></li>)}</ol> : <p>No recommendations yet. Upload a CV, then use lab matching.</p>}</section><aside className={styles["overview"]}><section className={styles["overviewSection"]}><div className={styles["overviewHeading"]}><h2>Upcoming dates</h2><Link href="/calendar">Calendar</Link></div>{upcoming.length ? <ol className={styles["deadlineList"]}>{upcoming.map((item) => <li key={`${item.type}-${item.title}`}><time>{new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(new Date(item.date))}</time><div><strong>{item.title}</strong><span>{item.type}</span></div></li>)}</ol> : <p>No upcoming dates.</p>}</section></aside></div></main>;
}
