"use client";

import ky, { HTTPError } from "ky";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

import type { LabSummary } from "../../server/backend/labs";
import { ProfessorSaveIcon } from "../professors/professor-save-icon";
import { getRecommendations, type Recommendation } from "../recommendations/recommendations-api";
import { RecommendationResults } from "../recommendations/recommendation-results";

type Props = Readonly<{ initialLabs: readonly LabSummary[]; initialTotal: number; initialQuery?: string; initialError?: boolean }>;
const formatter = new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeZone: "Asia/Seoul" });

async function apiLabs(query: string): Promise<{ items: LabSummary[]; total: number }> { const params = new URLSearchParams({ page: "1", page_size: "100" }); if (query.trim()) params.set("q", query.trim()); return ky.get(`/api/backend/labs?${params}`).json(); }

function LabCard({ lab, saved, saving, onToggle }: Readonly<{ lab: LabSummary; saved: boolean; saving: boolean; onToggle: (id: string, next: boolean) => Promise<void> }>) {
  const saveLabel = saving ? (saved ? "Removing saved lab" : "Saving lab") : saved ? "Remove saved lab" : "Save lab";
  return <article className="catalog-card"><div className="catalog-card-heading"><div><div className="catalog-card-meta"><span>{lab.university}</span><span>{lab.department}</span></div><h2>{lab.name}</h2><p>{lab.professorName} · {lab.field}</p></div><div className="catalog-card-actions"><Link className="catalog-detail-link" href={`/professors/${lab.id}`}>View details</Link>{lab.homepageUrl && <a className="catalog-lab-link" href={lab.homepageUrl} rel="noreferrer" target="_blank">Lab website</a>}<button aria-busy={saving} aria-label={saveLabel} aria-pressed={saved} className={"catalog-save-button" + (saved ? " is-saved" : "")} disabled={saving} onClick={() => void onToggle(lab.id, !saved)} title={saveLabel} type="button"><ProfessorSaveIcon saved={saved} /></button></div></div>{lab.summary && <p>{lab.summary}</p>}<ul aria-label={`${lab.name} research keywords`} className="catalog-topic-list">{lab.keywords.map((keyword) => <li key={keyword}>{keyword}</li>)}</ul><div className="catalog-source-row"><span>POSTECH catalogue data</span><span className="catalog-source-date">Updated {formatter.format(new Date(lab.updatedAt))}</span></div></article>;
}

export function LabCatalogExplorer({ initialLabs, initialTotal, initialQuery = "", initialError = false }: Props) {
  const [query, setQuery] = useState(initialQuery); const [labs, setLabs] = useState(initialLabs); const [total, setTotal] = useState(initialTotal); const [status, setStatus] = useState<"idle" | "loading" | "error">(initialError ? "error" : "idle"); const [savedIds, setSavedIds] = useState<readonly string[]>([]); const [savingId, setSavingId] = useState<string | null>(null); const [saveStatus, setSaveStatus] = useState(""); const [recommendations, setRecommendations] = useState<readonly Recommendation[] | null>(null); const [recommendationStatus, setRecommendationStatus] = useState<"idle" | "loading" | "error" | "missing-cv" | "unauthorized">("idle");
  const loadFavorites = useCallback(async () => { try { const result = await ky.get("/api/backend/me/favorites").json<{ labIds: string[] }>(); setSavedIds(result.labIds); } catch (error) { if (error instanceof HTTPError && error.response.status === 401) setSaveStatus("Log in to manage saved labs."); else setSaveStatus("Could not load saved labs."); } }, []);
  useEffect(() => { void Promise.resolve().then(loadFavorites); }, [loadFavorites]);
  useEffect(() => { const handle = window.setTimeout(() => { void (async () => { setStatus("loading"); try { const result = await apiLabs(query); setLabs(result.items); setTotal(result.total); setStatus("idle"); } catch { setStatus("error"); } })(); }, 250); return () => window.clearTimeout(handle); }, [query]);
  async function toggle(id: string, next: boolean) { setSavingId(id); try { await (next ? ky.put(`/api/backend/me/favorites/${id}`) : ky.delete(`/api/backend/me/favorites/${id}`)); setSavedIds((current) => next ? [...new Set([...current, id])] : current.filter((item) => item !== id)); setSaveStatus(next ? "Saved lab." : "Removed saved lab."); } catch (error) { if (error instanceof HTTPError && error.response.status === 401) window.location.assign("/login"); else setSaveStatus("Could not update saved labs. Your previous state was kept."); } finally { setSavingId(null); } }
  async function loadRecommendations() { setRecommendationStatus("loading"); try { setRecommendations(await getRecommendations()); setRecommendationStatus("idle"); } catch (error) { setRecommendationStatus(error instanceof HTTPError && error.response.status === 409 ? "missing-cv" : error instanceof HTTPError && error.response.status === 401 ? "unauthorized" : "error"); } }
  return <main className="catalog-page"><header className="catalog-hero"><p className="catalog-kicker">POSTECH LAB DISCOVERY</p><h1>Find labs aligned with your research</h1><p>Search validated POSTECH lab data and review each source before deciding.</p></header><div className="catalog-workspace"><section className="catalog-result-toolbar" aria-label="CV recommendations"><p><strong>Match with my CV</strong> to see the server-provided explanation.</p><button className="catalog-clear-button" disabled={recommendationStatus === "loading"} onClick={() => void loadRecommendations()} type="button">{recommendationStatus === "loading" ? "Loading recommendations" : "Match with my CV"}</button></section>{recommendationStatus === "missing-cv" && <section className="catalog-empty"><h2>Analyze your CV first</h2><Link href="/cv">Go to CV analysis</Link></section>}{recommendationStatus === "unauthorized" && <section className="catalog-empty"><h2>Your session has expired</h2><Link href="/login">Log in</Link></section>}{recommendationStatus === "error" && <section className="catalog-empty" role="alert"><h2>Could not load recommendations</h2><button onClick={() => void loadRecommendations()} type="button">Try again</button></section>}{recommendations && <RecommendationResults items={recommendations} />}<label className="catalog-search-field"><span>Search labs, professors, or keywords</span><input onChange={(event) => setQuery(event.target.value)} placeholder="e.g. vision, robotics, AI" type="search" value={query} /></label><div className="catalog-results-area"><div className="catalog-result-toolbar"><p aria-live="polite"><strong>{status === "loading" ? "Loading" : total}</strong> {status === "loading" ? "labs…" : "labs found"}</p></div><p className="catalog-save-status" aria-live="polite">{saveStatus}</p>{status === "error" ? <section className="catalog-empty" role="alert"><h2>Could not load labs</h2><button onClick={() => setQuery((value) => `${value} `)}>Try again</button></section> : labs.length ? <section aria-label="Lab search results" className="catalog-grid">{labs.map((lab) => <LabCard key={lab.id} lab={lab} saved={savedIds.includes(lab.id)} saving={savingId === lab.id} onToggle={toggle} />)}</section> : status === "idle" ? <section className="catalog-empty"><h2>No labs match this search</h2><p>Try a shorter or different keyword.</p></section> : null}</div></div></main>;
}
