"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { getLatestAnalysis, getProfile, saveProfile, type DocumentAnalysis, type UserProfile, WorkspaceApiError } from "../workspace/api";

export function RealProfileWorkspace() {
  const [profile, setProfile] = useState<UserProfile | null>(null); const [analysis, setAnalysis] = useState<DocumentAnalysis | null>(null); const [state, setState] = useState("loading"); const [message, setMessage] = useState("");
  useEffect(() => { void Promise.all([getProfile(), getLatestAnalysis().catch((error: WorkspaceApiError) => error.status === 404 ? null : Promise.reject(error))]).then(([next, cv]) => { setProfile(next); setAnalysis(cv); setState("ready"); }).catch((error: WorkspaceApiError) => { setState(error.status === 401 ? "unauthorized" : "error"); setMessage(error.message); }); }, []);
  if (state === "loading") return <main className="profile-layout"><p role="status">Loading your profile…</p></main>;
  if (state === "unauthorized") return <main className="profile-layout"><p>You need to log in to view your profile.</p><Link href="/login">Log in</Link></main>;
  if (!profile) return <main className="profile-layout"><p role="alert">{message || "Profile unavailable."}</p></main>;
  async function submit(data: FormData): Promise<void> { setState("saving"); try { const next = await saveProfile({ name: String(data.get("name") || ""), affiliation: String(data.get("affiliation") || ""), status: String(data.get("status") || ""), program: String(data.get("program") || ""), interests: String(data.get("interests") || "").split(",").map((item) => item.trim()).filter(Boolean) }); setProfile(next); setMessage("Profile saved."); setState("ready"); } catch (error) { const apiError = error as WorkspaceApiError; setMessage(apiError.status === 401 ? "Your session has expired. Please log in again." : "Could not save your profile. Your edits were not applied."); setState("ready"); } }
  return <main className="profile-layout"><section className="profile-intro"><p className="kicker">MY RESEARCH PROFILE</p><h1>{profile.name || "Your"} profile</h1><p>Keep your application information and CV analysis in one place.</p></section><form className="profile-card" action={(form) => void submit(form)}><label className="field">Name<input name="name" required defaultValue={profile.name} /></label><label className="field">Affiliation<input name="affiliation" defaultValue={profile.affiliation} /></label><label className="field">Program<input name="program" defaultValue={profile.program} /></label><label className="field">Status<input name="status" defaultValue={profile.status} /></label><label className="field">Research interests (comma-separated)<input name="interests" defaultValue={profile.interests.join(", ")} /></label><button className="primary-button" disabled={state === "saving"} type="submit">{state === "saving" ? "Saving…" : "Save profile"}</button><p aria-live="polite">{message}</p></form><section className="profile-card"><h2>Latest CV analysis</h2>{analysis ? <><p>{analysis.original_filename || "CV"}</p><p>{analysis.short_summary}</p><p><strong>Skills:</strong> {analysis.skills.join(", ") || "None extracted"}</p><p><strong>Research interests:</strong> {analysis.research_interests.join(", ") || "None extracted"}</p></> : <><p>No CV analysis is available yet.</p><Link href="/cv">Upload and analyze a CV</Link></>}</section></main>;
}
